version: "3.8"

services:
  backend:
    image: waengs/finalprojectwads-backend:latest
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      DENSER_API_KEY: ${DENSER_API_KEY}
      DENSER_CHATBOT_ID: ${DENSER_CHATBOT_ID}
    ports:
      - "3002:3002"

  frontend:
    image: waengs/finalprojectwads-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"